### ISSUE TITLE
query by date (since and until) seems returns less data by just query keywords

### ISSUE THREAD

**Issue by tonywangcn** [jonbakerfish/TweetScraper#9] opened 2017-09-16 05:25 UTC
![image](https://user-images.githubusercontent.com/3056655/30509383-f0dbfec8-9a74-11e7-9f08-e7ff49862ea3.png)
the pic shows that, from 08.22 to 09.11 , the tweets every day queried by date is so smoothy, compared the last few days queried by just keywords.

Perhaps it's policy of Twitter, have you guys ever had this kind of problems?

**Comment by jonbakerfish** [comment] 2017-09-16 05:42
> last few days queried by just keywords.

Without `since` and `until`, you are crawling all the tweets. In this plot, are you counting the tweets sent on Sep 12-16 or all crawled tweets?

**Comment by tonywangcn** [comment] 2017-09-16 06:12
Say, I started a crawler of "query=keyword" in 09.15. It was crawlling all the tweets contains "keyword". In the same time , several crawlers of "query=keyword since:2017-08-12 until:2017-08-13" were crawling, until it's "query=keyword since:2017-09-11 until:2017-09-12". All the tweets before 09-12 is generated by these parallel crawlers( since and until). After some hours or days crawling. The first (single one without dates) crawler stoped in 09-12 or nearby .Results in plot shows that, Twitter will limit the max number of tweets queried by dates, not yet confirmed.

**Comment by davistamu** [comment] 2017-10-02 00:42
I run "scrapy crawl TweetScraper -a query=Harvey OR Hurricane", it returns "crawl: error: running 'scrapy crawl' with more than one spider is no longer supported". I don't know what's wrong with the code.

**Comment by emrecalisir** [comment] 2018-01-27 20:31
I had the same problem, I executed the command with the parameters of since:2016-06-01 until:2016-07-01. But it terminated the process after retrieving tweets only between 2016-06-25 and 2016-07-01. Should I select weekly periods or is there a max limit number set by Twitter for crawling operation.

**Comment by D4thor** [comment] 2019-02-13 16:46
did you guys find a solution? I am facing the same problem right now regarding #ArtificialIntelligence.

When I just let the API run (which limits the access to the last 7 days) with an API Crawler using the search API, I got an average like 50k Tweets per day (roughly).
When I use "query=#ArtificialIntelligence, Artificial Intelligence until:2016-03-30" with the Scraper here, I receive only 300-400 Tweets per day for a whole year. I accidently crawled 110.000 Tweets until 2015-01-12, because it went so fast. 
I mean, of course, Tweets on #ArtificialIntelligence might have increased in the last years, but for sure not in the ratio (50.000 / 350 = 143)

**Comment by saggel** [comment] 2019-02-18 08:53
I'm trying this now too and have the same issue!

I think the problem is on the file: `/spiders/TweetCrawler.py` on the line 29:

`self.url = "https://twitter.com/i/search/timeline?l={}".format(lang)`

I think the url is wrong! 

By manually searching it should be:

`https://twitter.com/search?q={}&lang=(lang)`

But I could be wrong - think it's probably a good place to start for a fix though

**Comment by D4thor** [comment] 2019-02-18 11:23
Thanks for the suggestion. So far I just changed the URL to the URL proposed by you, but, in deed, there seems to be a lot more debugging needed, since its just blowing up: 

`(venv) (base) C:\Users\_MyUser_Projekte\TweetScraper-master\TweetScraper>scrapy crawl TweetScraper -a query="Artificial Intelligence,#ArtificialIntelligence"
2019-02-18 12:16:01 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: TweetScraper)
2019-02-18 12:16:01 [scrapy.utils.log] INFO: Versions: lxml 4.3.0.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 18.9.0, Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.1a  20 Nov 2018), cryptography 2.4.2, Platform Windows-10-10.0.17134-SP0
2019-02-18 12:16:01 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'TweetScraper', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'TweetScraper.spiders', 'SPIDER_MODULES': ['TweetScraper.spiders'], 'USER_AGENT': 'Student/research_for_thesis'}
2019-02-18 12:16:01 [scrapy.extensions.telnet] INFO: Telnet Password: fc679cb884396874
2019-02-18 12:16:01 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-02-18 12:16:02 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-02-18 12:16:02 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-02-18 12:16:02 [scrapy.middleware] INFO: Enabled item pipelines:
['TweetScraper.pipelines.SaveToFilePipeline']
2019-02-18 12:16:02 [scrapy.core.engine] INFO: Spider opened
2019-02-18 12:16:02 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-02-18 12:16:02 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-02-18 12:16:03 [scrapy.core.scraper] ERROR: Spider error processing <GET https://twitter.com/search-home> (referer: None)
Traceback (most recent call last):
  File "c:\users\_MyUser_\projekte\tweetscraper-master\tweetscraper\venv\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\users\_MyUser_\projekte\tweetscraper-master\tweetscraper\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\users\_MyUser_\projekte\tweetscraper-master\tweetscraper\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\users\_MyUser_\projekte\tweetscraper-master\tweetscraper\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\_MyUser_\projekte\tweetscraper-master\tweetscraper\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\_MyUser_\Projekte\TweetScraper-master\TweetScraper\spiders\TweetCrawler.py", line 50, in parse_page
    data = json.loads(response.body.decode("utf-8"))
  File "C:\Users\_MyUser_\Anaconda3\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\_MyUser_\Anaconda3\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\_MyUser_\Anaconda3\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-02-18 12:16:03 [scrapy.core.engine] INFO: Closing spider (finished)
2019-02-18 12:16:03 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 958,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 39442,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/302': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 2, 18, 11, 16, 3, 457730),
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'response_received_count': 1,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/JSONDecodeError': 1,
 'start_time': datetime.datetime(2019, 2, 18, 11, 16, 2, 766366)}
2019-02-18 12:16:03 [scrapy.core.engine] INFO: Spider closed (finished)`

**Comment by saggel** [comment] 2019-02-18 11:31
I've tried a few options too - now I'm on:

`self.url = "https://twitter.com/search?f=tweets&vertical=default&q={}".format(lang)`

which I think it's getting close - no bugs, but it doesn't collect tweets!
Maybe the developer can help us? @jonbakerfish?

**Comment by D4thor** [comment] 2019-02-19 12:05
@saggel btw, did you find a way to write all the Tweets into one file (preferably json) instead of creating one file per tweet? That would be a lot easier to analyze all the results

**Comment by saggel** [comment] 2019-02-19 13:00
> @saggel btw, did you find a way to write all the Tweets into one file (preferably json) instead of creating one file per tweet? That would be a lot easier to analyze all the results

I write on a MySQL database and use R to connect to it and run the analytics I need!

**Comment by saggel** [comment] 2019-02-19 13:02
> I've tried a few options too - now I'm on:
> 
> `self.url = "https://twitter.com/search?f=tweets&vertical=default&q={}".format(lang)`
> 
> which I think it's getting close - no bugs, but it doesn't collect tweets!
> Maybe the developer can help us? @jonbakerfish?

on another note, I think the link is fine but the problem might be at the min/max positions!

**Comment by D4thor** [comment] 2019-02-19 13:36
> > @saggel btw, did you find a way to write all the Tweets into one file (preferably json) instead of creating one file per tweet? That would be a lot easier to analyze all the results
> 
> I write on a MySQL database and use R to connect to it and run the analytics I need!

Oh, that's even better. I would love to write to a MySQL database as well, but I am new to Python and didn't figure out yet where and how to change the code.
Would you mind sharing the code part that you adapted to write to the MySQL database?
Thanks!

**Comment by saggel** [comment] 2019-02-19 13:41
> > > @saggel btw, did you find a way to write all the Tweets into one file (preferably json) instead of creating one file per tweet? That would be a lot easier to analyze all the results
> > 
> > 
> > I write on a MySQL database and use R to connect to it and run the analytics I need!
> 
> Oh, that's even better. I would love to write to a MySQL database as well, but I am new to Python and didn't figure out yet where and how to change the code.
> Would you mind sharing the code part that you adapted to write to the MySQL database?
> Thanks!

Sure, it's on settings.py

```
ITEM_PIPELINES = {
    # 'TweetScraper.pipelines.SaveToFilePipeline':100,
    #'TweetScraper.pipelines.SaveToMongoPipeline':100, # replace `SaveToFilePipeline` with this to use MongoDB
    'TweetScraper.pipelines.SavetoMySQLPipeline':100, # replace `SaveToFilePipeline` with this to use MySQL
}
```

**Comment by D4thor** [comment] 2019-02-19 16:24
> > > > @saggel btw, did you find a way to write all the Tweets into one file (preferably json) instead of creating one file per tweet? That would be a lot easier to analyze all the results
> > > 
> > > 
> > > I write on a MySQL database and use R to connect to it and run the analytics I need!
> > 
> > 
> > Oh, that's even better. I would love to write to a MySQL database as well, but I am new to Python and didn't figure out yet where and how to change the code.
> > Would you mind sharing the code part that you adapted to write to the MySQL database?
> > Thanks!
> 
> Sure, it's on settings.py
> 
> ```
> ITEM_PIPELINES = {
>     # 'TweetScraper.pipelines.SaveToFilePipeline':100,
>     #'TweetScraper.pipelines.SaveToMongoPipeline':100, # replace `SaveToFilePipeline` with this to use MongoDB
>     'TweetScraper.pipelines.SavetoMySQLPipeline':100, # replace `SaveToFilePipeline` with this to use MySQL
> }
> ```
> and on pipelines.py
> 
> ```
> class SavetoMySQLPipeline(object):
> 
>     ''' pipeline that save data to mysql '''
>     def __init__(self):
>         # connect to mysql server
>         user = 'username'
>         pwd = 'password'
>         self.cnx = mysql.connector.connect(user=user, password=pwd,
>                                 host='localhost',
>                                 database='tweets', buffered=True)
>         self.cursor = self.cnx.cursor()
>         self.table_name = raw_input("Table name: ")
>         create_table_query =   "CREATE TABLE `" + self.table_name + "` (\
>                 `ID` CHAR(20) NOT NULL,\
>                 `url` VARCHAR(140) NOT NULL,\
>                 `datetime` VARCHAR(22),\
>                 `text` VARCHAR(500),\
>                 `user_id` CHAR(20) NOT NULL,\
>                 `usernameTweet` VARCHAR(20) NOT NULL\
>                 )"
> ```

Thanks, but I mixed the SQL names up. My actual plan was to use SQLite, but I guess it should work in a similar way with some minor code adjustments .:)

**Comment by D4thor** [comment] 2019-02-23 09:46
@saggel Do you know if it is possible to scrawl the geodata for each tweet as well? I mean advanced search in general has this option, but the returned tweet item doesn't contain any field with geodata.

**Comment by Q00** [comment] 2019-09-19 17:16
> > I've tried a few options too - now I'm on:
> > `self.url = "https://twitter.com/search?f=tweets&vertical=default&q={}".format(lang)`
> > which I think it's getting close - no bugs, but it doesn't collect tweets!
> > Maybe the developer can help us? @jonbakerfish?
> 
> on another note, I think the link is fine but the problem might be at the min/max positions!

Hi, I wanna know How to use that url. I think that url use bearer token and there is no max position. Max position is just empty. How to use that? I think the url that TweetScraper uses is disallowed by Twitter robots.txt. I am keen on getting right url. please help me!

**Closed** 2020-09-30 02:08 UTC
